# Everforest Dark Hard theme for Fuzzel

[main]
font = "Terminess Nerd Font Mono:size=14"
minimal-lines = "True"
width = 24

[colors]
background=1E2326FF
text=D3C6AAFF
prompt=D3C6AAFF
placeholder=838ba7ff
input=D3C6AAFF
match=A7C080FF
selection=D3C6AAFF
selection-text=1E2326FF
selection-match=E67E80FF
counter=A7C080FF
border=A7C080FF

[border]
width=2
radius=5
